### PR TITLE
Kjørt make template_init

### LINKED ISSUE #6: Run template_init
## Feature description
Run terraform init
## Checklist (after created issue)
- [x] Added label(s)
- [ ] Added to project
- [x] Added to milestone

### PR DESCRIPTION
**Pull request by karimacherradi**
## Closes/fixes/resolves issue(s)?
Closes #6 
## Checklist (after created PR)
- [x] Added reviewers
- [x] Added assignee(s)
- [x] Added label(s)
- [ ] Added to project
- [x] Added to milestone
- Need to update documentation? (Y/n)

### CODE REVIEW

**Review by hannemariavister — COMMENTED** [review]
I think you have forgot to update CHANGELOG.md with your changes?

**Comment by karimacherradi** [comment]
>Done

**Comment by hannemariavister** [comment]
I cannot see that [02_run_terraform.yml](https://github.com/hannemariavister/terraform-nomad-nifiregistry/blob/1fd06bb44a90139a4c869c012fa54c9cd0a517ca/template_example/dev/ansible/02_run_terraform.yml) is executed, because there exists no example in `/example/standalone/`. Should this PR contain example/standalone?

**Comment by karimacherradi** [comment]
> I cannot see that [02_run_terraform.yml](https://github.com/hannemariavister/terraform-nomad-nifiregistry/blob/1fd06bb44a90139a4c869c012fa54c9cd0a517ca/template_example/dev/ansible/02_run_terraform.yml) is executed, because there exists no example in `/example/standalone/`. Should this PR contain example/standalone?

I just run step 3 as mentioned in documentation:
https://github.com/hannemariavister/terraform-nomad-nifiregistry/blob/master/README.md#quick-start

**Review by hannemariavister — APPROVED** [review]

**Pull request merged**
